name: ci
on:
  push:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
    - run: |
        curl -s https://raw.githubusercontent.com/OriHoch/uumpa-ci-toolbox/main/bin/github_actions_install.sh | bash -s "${GITHUB_SHA}" &&\
        uci github actions self-checkout &&\
        uci github actions docker-login &&\
        uci docker build-cache --cache-from ghcr.io/orihoch/uumpa-ci-toolbox/uci -t uci . &&\
        uci docker tag-push uci "ghcr.io/orihoch/uumpa-ci-toolbox/uci:${GITHUB_SHA}" &&\
        if [ "$(uci github actions get-branch-name)" == "main" ]; then
          uci docker tag-push uci "ghcr.io/orihoch/uumpa-ci-toolbox/uci:latest"
        fi
