name: ci
on:
  push:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  UCI_DEPLOY_KEY: ${{ secrets.UCI_DEPLOY_KEY }}
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
    - run: |
        curl -s https://raw.githubusercontent.com/OriHoch/uumpa-ci-toolbox/main/bin/github_actions_install.sh | bash -s "${GITHUB_SHA}" &&\
        uci github actions self-checkout --config-user-name "uumpa-ci-toolbox-ci" &&\
        if ! uci git check-last-commit-message --equals "automatic version update"; then
          echo "UCI_VERSION = '${GITHUB_SHA}'" > uumpa_ci_toolbox/version.py &&\
          uci github actions docker-login &&\
          uci docker build-cache --cache-from ghcr.io/orihoch/uumpa-ci-toolbox/uci -- -t uci . &&\
          uci docker tag-push uci "ghcr.io/orihoch/uumpa-ci-toolbox/uci:${GITHUB_SHA}" &&\
          if [ "$(uci github actions get-branch-name)" == "main" ]; then
            uci docker tag-push uci "ghcr.io/orihoch/uumpa-ci-toolbox/uci:latest" &&\
            git add uumpa_ci_toolbox/version.py &&\
            git commit -m "automatic version update" &&\
            git push
          fi
        fi
